#!/usr/bin/env bash
#Comment
file="apache-access.log"

if [ ! -f "$file" ]; then
    echo "Error: $file not found!"
    exit 1
fi

# Remove carriage returns, count occurrences, sort
awk '{gsub("\r",""); count[$1" "$9]++} END {for (k in count) print count[k], k}' "$file" | sort -rn
