#!/usr/bin/env bash
# This script creates PID file, displays messages, and handles signals

# Create PID file
echo $$ > /var/run/myscript.pid

# Set up signal handlers
trap "echo 'I hate the kill command'; rm /var/run/myscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm /var/run/myscript.pid; exit" SIGQUIT

# Main loop
while true
do
  echo "To infinity and beyond"
  sleep 2
done
