#!/usr/bin/env bash
# shellcheck disable=SC2044
for pid in $(find /proc -maxdepth 1 -type d -regex '/proc/[0-9]+'); do
    pidnum=$(basename "$pid")
    if [ -r "/proc/$pidnum/comm" ]; then
        name=$(<"/proc/$pidnum/comm")
        if [ "$name" = "bash" ]; then
            echo "$pidnum $name"
        fi
    fi
done
