#!/usr/bin/env bash
#comment
for pid in $(ls /proc | grep '^[0-9]*$'); do
    if [ -f "/proc/$pid/comm" ]; then
        name=$(cat "/proc/$pid/comm")
        if [ "$name" = "bash" ]; then
            echo "$pid $name"
        fi
    fi
done
